spring.application.name=verirun
spring.profiles.active=api,worker

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=
spring.data.redis.port=

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

app.verification.base-url=http://localhost:8080/api/auth
app.workspace.base-path=./verirun-workspace

spring.cloud.aws.s3.region=

app.storage.bucket-name=
app.queue.job-name=
app.verilator.uvm-home=

app.worker.build-timeout-seconds=120
app.worker.run-timeout-seconds=60
app.worker.max-memory-bytes=536870912
app.worker.cpu-limit=1
app.worker.max-log-size=100000
app.worker.job-timeout-seconds=180
app.worker.max-retries=2
app.docker.verilator-image=

#Email properties
#spring.mail.host=
#spring.mail.port=
#spring.mail.username=
#spring.mail.password=
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.protocol=smtp
#spring.mail.properties.mail.tls=true
#spring.mail.properties.mail.smtp.ssl.trust=